name: Build and Push Docker Images using Docker Compose

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      # Define Postgres service here for the CI job
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: leave_attendance
        ports:
          - 5432:5432

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation
    
    # Set up Docker Compose
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
      with:
        version: 'latest'

    # Build and push the application and Postgres images using Docker Compose
    - name: Build and Push Docker Compose services
      run: |
        # Build the images using docker-compose
        docker-compose -f docker-compose.yaml build

        # Image names check
        docker images
        # Tag and push the app image to Docker Hub
        docker tag fastapi_app chloe315/2025cloud:fastapi_app
        docker push chloe315/2025cloud:fastapi_app
        
        # Tag and push the Postgres image to Docker Hub
        docker tag postgres:14 chloe315/2025cloud:postgres
        docker push chloe315/2025cloud:postgres
